version: '3.3'

services:
  data_base: #Container do banco de dados mysql
    image: mysql:5.7
    volumes:
      - db_data:/var/lib/mysql #criação de um named volumes
    restart: always # aplica as modificações feitas sempre que alteramos as configurações
    env_file:
      - ./config/db.env
  wordpress:
    depends_on: 
     - data_base
    image: wordpress:latest
    ports:
      - "8000:80"
    restart: always
    env_file:
      - ./config/wp.env
    
volumes:
  db_data: {} 